name: Deploy Azure Resources-Updated
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AUTO_AZURE_CLIENT_ID }} -p ${{ secrets.AUTO_AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AUTO_AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AUTO_AZURE_SUBSCRIPTION_ID }}
      
      - name: Install Bicep CLI
        run: az bicep install
      - name: Create Resource Group
        run: |
          az group create --name PSLCkmDraft --location eastus
      - name: Assign role
        run: |
          az role assignment create \
           --assignee ${{ secrets.AUTO_AZURE_CLIENT_ID }} \
           --role "User Access Administrator" \
           --scope /subscriptions/${{ secrets.AUTO_AZURE_SUBSCRIPTION_ID }}/resourceGroups/PSLCkmDraft
      - name: Deploy Bicep Template
        id: deploy
        run: |
          set -e
          az deployment group create \
            --resource-group PSLCkmDraft \
            --template-file Deployment/bicep/main.bicep \
            --parameters solutionPrefix=draft location=eastus
