name: Docker Image CI
on:
  push:
    branches:
    - master
    - dev

permissions: # Sets workflow permissions using the least privilege principle
  contents: read # Read access to repo, required by the actions/checkout@v2 action

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
        cd "GBB.ConversationalKM.Python";
        docker pull ${{ secrets.ACR_LOGIN_SERVER }}/csci-python-func:latest || true;
        docker build . --file Dockerfile --cache-from ${{ secrets.ACR_LOGIN_SERVER }}/csci-python-func:latest --tag ${{ secrets.ACR_LOGIN_SERVER }}/csci-python-func:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/csci-python-func:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ${{ secrets.ACR_LOGIN_SERVER }}/csci-python-func:latest;
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/csci-python-func:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/csci-python-func:latest
